### ISSUE TITLE
Licence and copyright?

### ISSUE THREAD

**Issue by boutil** [markaby/markaby#30]
Hi!

I cannot find any information in the files you distribute about the copyright and licence under which this project is published.
The (old) project page on rubyforge does not mention anything either. The current Debian package (corresponding to version 0.5) mentions "Copyright 2006 why the lucky stiff" and Licence MIT/Expat.

I would like to know if this is/was correct. If not, could you please mention clearly these informations?

Thank you very much in advance

Cédric

**Comment by smtlaissezfaire** [comment]
@judofyr I know you've done a lot with mab.  What would you think of combining projects?

**Comment by smtlaissezfaire** [comment]
It seems silly to duplicate effort on two different projects.

**Comment by judofyr** [comment]
@smtlaissezfaire not quite sure. `mab` uses a completely different approach and is already mostly feature-complete.

**Comment by smtlaissezfaire** [comment]
That link to the mailing list archive no longer seems public.

As far as I understand, without a license it's public domain.

Since _why has been gone and I seem to be the only one working on it, I'm going forward with it using the MIT license.  New release will be coming soon.
