### ISSUE TITLE
duplicate key :object in hash

### ISSUE THREAD

**Issue by chaomao** [markaby/markaby#35]
lib/markaby/tags.rb:265

``` ruby
      :object => [:form],
      :ol => [:reversed],
      :object => [:typemustmatch],
```

I think it should be typo

**Comment by stugol** [comment]
Well, this bug has existed for almost TWELVE MONTHS so far, and not been fixed. Indeed, I see no movement on this codebase for two years. Is this project completely fucking dead?

If so, kindly stop WASTING EVERYONE'S DAMN TIME and put a note at the top of the readme, warning people not to bother trying to use it!

**Comment by smtlaissezfaire** [comment]
Hi @stugal

I took over as maintainer several years ago when _why left the community.

I haven't had time to work on this project, but I'd be happy to take patches and find other maintainers for it.

Submit a patch and I'll make you a maintainer.
