### ISSUE TITLE
Tag missing for v0.9.0

### ISSUE THREAD

**Issue by o314** [markaby/markaby#40]
Hello Markaby developers.

I have not found any tag / release for the v0.9.0 on github.

The gem is available and a commit has been made https://github.com/markaby/markaby/commit/3a1f0768517042ea45182aaf7916e15e53dc427f

Is there any way to correct that ?

**Comment by rahoulb** [comment]
@smtlaissezfaire Just to add to this - I tried adding the gem to a new project today and, while it loaded v0.9.0 - the released version of the gem doesn't include the latest changes.  The gem needs a version bump and re-release.  Cheers.

**Comment by diclophis** [comment]
For what it is worth, if this project is seeking more maintainers I would be interested in helping out... I am a huge fan of this style of html document generation.
