### ISSUE TITLE
Is it possible to use custom attributes

### ISSUE THREAD

**Issue by kmafeni04** [markaby/markaby#46]
Is it possible to set custom attributes to use with libraries like htmx and alpine>
e.g:
```ruby
div do
  button(hx_get: '/test') do
    'test'
  end
end
```

**Comment by diclophis** [comment]
It should be possible to make use of the `data-` html attribute prefix...

Something to the effect of...

```ruby
doc = mab do
  html5 do
    div(data: {"hx_get" => "/test"})
  end
end

# doc should include '<div data-hx-get="/test">'
  ```

The htmx documentation currently lists support for using the `data-` prefix near the bottom of this section of their docs: https://htmx.org/docs/#introduction
  
![image](https://github.com/markaby/markaby/assets/10122/3d1a8715-d3bd-45b6-b29a-7ac3c351831f)

**Comment by smtlaissezfaire** [comment]
I think these parts of the README might be relevant:

https://github.com/markaby/markaby?tab=readme-ov-file#6-the-tag-method-
https://github.com/markaby/markaby?tab=readme-ov-file#custom-elements-and-web-components-

**Comment by kmafeni04** [comment]
> https://github.com/markaby/markaby?tab=readme-ov-file#6-the-tag-method- 
Same issue as just using the regular button method

> https://github.com/markaby/markaby?tab=readme-ov-file#custom-elements-and-web-components-
This allows me to use hx-get on custom elements but custom html elements aren't something I'll frequenty uses, especially for something like a button
